@startuml
autonumber
actor "Warehouse Employee" as WE

activate WE
WE -> ":System" : starts set up the warehouse plant
activate ":System"
":System" --> WE : requests data (path of the JSON file, warehouseName)
deactivate ":System"

WE -> ":System" : types requested data
activate ":System"
":System" --> WE : imports the data and shows it
deactivate ":System"

WE -> ":System" : visualizes the data
activate ":System"
":System" --> WE : informs operation success
deactivate ":System"

deactivate WE

@enduml